version: "2"
services:
    nginx:
        image: nginx
        container_name: "laravel-nginx"
        ports:
            - "20000:80"
        volumes:
            - ./src:/src
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
        build: ./php
        container_name: "laravel-php"
        volumes:
            - ./src:/src
    mysql:
        image: mysql
        container_name: "laravel-mysql"
        environment:
            MYSQL_DATABASE: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "20001:3306"
